gcc-sdk/gcc: fix build breakage on x86
Change-Id: I27bf66b7640783059d91fafe6cb07fa354abba73
Signed-off-by: Shilin Victor <chrono.monochrome@gmail.com>

diff --git a/gcc-sdk/gcc b/gcc-sdk/gcc
--- a/gcc-sdk/gcc
+++ b/gcc-sdk/gcc
@@ -20,21 +20,21 @@ suffix_m64=${options##* -m64 }    # suffix after the last -m64
 len_m32=${#suffix_m32}            # length of suffix after the last -m32
 len_m64=${#suffix_m64}            # length of suffix after the last -m64
 
-if [ $len_m32 -ge $len_m64 ] ; then
+#if [ $len_m32 -ge $len_m64 ] ; then
   # Choose 64-bit if -m64 only, -m64 appears after -m32, or neither exist (-eq)
-  MY_TOOL=`dirname $0`/${PREFIX64}-${PROGNAME}
+#  MY_TOOL=`dirname $0`/${PREFIX64}-${PROGNAME}
   # Make sure host is running 64-bit OS.
   # Note that "uname -m" only show host CPU is capable of.  Use the following technique
   # from ndk/build/core/ndk-common.sh instead
-  file -L "$SHELL" | grep -q "x86[_-]64"
-  if [ $? != 0 ]; then
+#  file -L "$SHELL" | grep -q "x86[_-]64"
+#  if [ $? != 0 ]; then
     # $SHELL is not a 64-bit executable, so assume our userland is too.
-    echo "ERROR: $MY_TOOL only run on 64-bit linux"
-    exit 1
-  fi
-else
+#    echo "ERROR: $MY_TOOL only run on 64-bit linux"
+#    exit 1
+#  fi
+#else
   # Otherwise, choose 32-bit
   MY_TOOL=`dirname $0`/${PREFIX32}-${PROGNAME}
-fi
+#fi
 
 $MY_TOOL "$@"
